services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EventManagerBundle\EventManager: ~

    EventManagerBundle\EventSubscriber\:
        resource: '../../EventSubscriber'
